# Auditoria de culturas, biomas e suporte

In [1]:
from pathlib import Path
import sys, numpy as np, pandas as pd
p=Path.cwd(); sys.path.insert(0,str(p.parent/'testes2'))
from metodos import Experimento, projetar
from apoio import preparar, ajustar
e=Experimento(p); d=preparar(e.d)
# Mesmos casos completos nos dois destinos, sem preencher faltantes.
comuns=['pp_agricultura','pp_pastagem','x_soja','x_milho',*d.filter(like='biome_').columns]
s=d.dropna(subset=comuns).copy()
r=s.loc[s.biome_pantanal_share_i.le(1e-6)].copy()

# A reexecução substitui a tabela derivada de sensibilidades desta rodada.
(p/'CONTRASTES_SENSIBILIDADE.csv').write_text('id,contraste,covariancia,estimativa,se,p,ic95_inf,ic95_sup,df\n')

62

## 1 — Inventário e limites de mensuração

In [2]:
from apoio import auditar
auditar(d,s,r,p)

{'linhas': 3384, 'colunas_origem': 70, 'municipios': 141, 'duplicatas': 0, 'sha256_csv': 'bc396a4f394ae60d6883205f2ca6e8d33b59a4fb419fc5d667591374c8f1c730', 'sha256_aux_apenas_inventario': '72a0136434cbadf80b70a271f5afd7f9fb9232458b5d6861517221564828ec6b', 'algodao_colunas': [], 'fracao_soma_erro_max': 0.001254790389649707, 'fracao_faltantes': 0, 'fracao_invariante': True, 'fracao_min': 0.0, 'fracao_max': 1.0000000000000084, 'conversao_cultura_disponivel': False, 'geometria_json_municipios': False, 'arquivos_geograficos_stats': []}

,amostra,grupo,N,municipios,informativos,anos,ano_min,ano_max
0,grade,Amazônia,1824,76,76,24,2001,2024
1,grade,Cerrado,1464,61,61,24,2001,2024
2,grade,Pantanal,96,4,4,24,2001,2024
3,grade,misto_1e-06_False,1872,78,78,24,2001,2024
4,grade,misto_1e-06_True,1512,63,63,24,2001,2024
5,grade,misto_0.05_False,2328,97,97,24,2001,2024
6,grade,misto_0.05_True,1056,44,44,24,2001,2024
7,grade,misto_0.1_False,2496,104,104,24,2001,2024
8,grade,misto_0.1_True,888,37,37,24,2001,2024
9,completa,Amazônia,1306,74,71,24,2001,2024
10,completa,Cerrado,1412,60,60,24,2001,2024
11,completa,Pantanal,54,3,3,24,2001,2024
12,completa,misto_1e-06_False,1634,77,77,24,2001,2024
13,completa,misto_1e-06_True,1138,60,57,24,2001,2024
14,completa,misto_0.05_False,1956,96,94,24,2001,2024
15,completa,misto_0.05_True,816,41,40,24,2001,2024
16,completa,misto_0.1_False,2052,103,100,24,2001,2024
17,completa,misto_0.1_True,720,34,34,24,2001,2024
18,sem_Pantanal,Amazônia,1301,70,70,24,2001,2024
19,sem_Pantanal,Cerrado,1322,56,56,24,2001,2024
20,sem_Pantanal,misto_1e-06_False,1634,77,77,24,2001,2024
21,sem_Pantanal,misto_1e-06_True,989,49,49,24,2001,2024
22,sem_Pantanal,misto_0.05_False,1888,90,90,24,2001,2024
23,sem_Pantanal,misto_0.05_True,735,36,36,24,2001,2024
24,sem_Pantanal,misto_0.1_False,1983,96,96,24,2001,2024
25,sem_Pantanal,misto_0.1_True,640,30,30,24,2001,2024

## 2 — Amostra comum e distribuição

In [3]:
pd.read_csv(p/'SUPORTE.csv')

,amostra,grupo,N,municipios,informativos,anos,ano_min,ano_max
0,grade,Amazônia,1824,76,76,24,2001,2024
1,grade,Cerrado,1464,61,61,24,2001,2024
2,grade,Pantanal,96,4,4,24,2001,2024
3,grade,misto_1e-06_False,1872,78,78,24,2001,2024
4,grade,misto_1e-06_True,1512,63,63,24,2001,2024
5,grade,misto_0.05_False,2328,97,97,24,2001,2024
6,grade,misto_0.05_True,1056,44,44,24,2001,2024
7,grade,misto_0.1_False,2496,104,104,24,2001,2024
8,grade,misto_0.1_True,888,37,37,24,2001,2024
9,completa,Amazônia,1306,74,71,24,2001,2024
10,completa,Cerrado,1412,60,60,24,2001,2024
11,completa,Pantanal,54,3,3,24,2001,2024
12,completa,misto_1e-06_False,1634,77,77,24,2001,2024
13,completa,misto_1e-06_True,1138,60,57,24,2001,2024
14,completa,misto_0.05_False,1956,96,94,24,2001,2024
15,completa,misto_0.05_True,816,41,40,24,2001,2024
16,completa,misto_0.1_False,2052,103,100,24,2001,2024
17,completa,misto_0.1_True,720,34,34,24,2001,2024
18,sem_Pantanal,Amazônia,1301,70,70,24,2001,2024
19,sem_Pantanal,Cerrado,1322,56,56,24,2001,2024
20,sem_Pantanal,misto_1e-06_False,1634,77,77,24,2001,2024
21,sem_Pantanal,misto_1e-06_True,989,49,49,24,2001,2024
22,sem_Pantanal,misto_0.05_False,1888,90,90,24,2001,2024
23,sem_Pantanal,misto_0.05_True,735,36,36,24,2001,2024
24,sem_Pantanal,misto_0.1_False,1983,96,96,24,2001,2024
25,sem_Pantanal,misto_0.1_True,640,30,30,24,2001,2024

## Interpretação e limites
Resultados integrais e Holm estão em RESULTADOS.md e tabelas CSV. O objeto é conversão agregada, não específica de cultura. Interfaces são proxies administrativas. Testes conjuntos de interfaces/pastagem dependem da covariância; rodada7 examinará choques territoriais e tendências. IC pontuais e exploração adaptativa não permitem aceitar H1 causal.